spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/init_manage?useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379